### ISSUE TITLE
Issue with AdvancementManager()

### ISSUE THREAD

**Issue by ghost** [jely2002/StandaloneCrazyAdvancementsAPI#3]
Hello, isnt a bug per se, but when i do;

`AdvancedManager manager = new AdvancementManager(Player... player)` it said that has a private method so i cant acces to him :(

so the suggestion is make it public like the CrazyAdvancementsAPI

thanks for the time!

**Comment by jely2002** [comment]
Hi Nian36,

First of all i see a little mistake in your code. The type of the variable manager must be AdvancementManager instead of AdvancedManager. Now you have a type mismatch because you try to put an AdvancementManager in a variable that can only store the AdvancedManager type.

I suggest you change it to:
`AdvancementManager manager = new AdvancementManager(Player... players)`

For additional info on how to use this API see: [https://www.spigotmc.org/resources/crazy-advancements-api.51741/](https://www.spigotmc.org/resources/crazy-advancements-api.51741/)
But keep in mind [the changes](https://github.com/jely2002/StandaloneCrazyAdvancementsAPI/) this maven wrapper brings with.

Hope I helped!

**Comment by ghost** [comment]
Oh sry, typing error... this is:
![image](https://user-images.githubusercontent.com/55646095/104877059-be8e4400-5937-11eb-8ecd-a160a557f619.png)

**Comment by jely2002** [comment]
I see now. Turns out I have changed this from the original plugin as well. 
Instead of `AdvancementManager manager = new AdvancementManager(Player... players)`,
 you may use ` AdvancementManager manager = CrazyAdvancements.getNewAdvancementManager();`.

I have updated [the example in the README](https://github.com/jely2002/StandaloneCrazyAdvancementsAPI) with a full example of how to get this API working.

**Comment by ZockerAxel** [comment]
This is not a change you did to the original API, the public constructor is a recent addition to the original API, as it is unneccessary to have a method for getting a new manager instead of having a public constructor.

**Comment by jely2002** [comment]
I have changed the way an AdvancementManager gets created. It now follows the official documentation with the only difference being that you have to initialize the api first by creating a new CrazyAdvancements object.
